eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZoon: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
server:
  port: 8309
  
spring:
  application:
    name: driver-service