zuul:
  prefix: /api
  routes:
    db-service: 
      path: /db-service/**
      url: http://localhost:8305
    manager-service:
      path: /manager-service/**
      url: http://localhost:8306
    call-center-service:
      path: /call-center/**
      url: http://localhost:8307
    hr-service:
      path: /hr-center/**
      url: http://localhost:8308
    driver-service:
      path: /driver/**
      url: http://localhost:8309
      